"""API endpoint manifest for the dependency-free local router."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence


@dataclass(frozen=True)
class EndpointSpec:
    method: str
    path: str
    name: str
    description: str
    request_fields: Sequence[str] = field(default_factory=tuple)
    response_fields: Sequence[str] = field(default_factory=tuple)

    def as_record(self) -> Mapping[str, Any]:
        return {
            "method": self.method,
            "path": self.path,
            "name": self.name,
            "description": self.description,
            "request_fields": tuple(self.request_fields),
            "response_fields": tuple(self.response_fields),
        }


API_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec("GET", "/health", "health", "Router health check", response_fields=("ok", "service")),
    EndpointSpec("GET", "/runtime/status", "runtime_status", "Local runtime status"),
    EndpointSpec("POST", "/runtime/tick", "runtime_tick", "Advance local runtime tick"),
    EndpointSpec("GET", "/agents", "agents_list", "List registered agent cards"),
    EndpointSpec("GET", "/agents/{did}", "agents_get", "Get a registered agent card"),
    EndpointSpec("GET", "/agents/{did}/memory", "agent_memory", "Get local memory records for an agent"),
    EndpointSpec("GET", "/agents/{did}/skills", "agent_skills", "Get skills associated with an agent"),
    EndpointSpec("POST", "/agents/{did}/run", "agent_run", "Run a local agent cycle placeholder"),
    EndpointSpec("POST", "/agents/launch", "agents_launch", "Launch a local agent through the API", request_fields=("goal", "name", "identity", "autonomy_mode")),
    EndpointSpec("POST", "/agents/launch-flowlang", "agents_launch_flowlang", "Launch a FlowLang-declared agent through the API", request_fields=("source", "goal")),
    EndpointSpec("POST", "/agents/launch-neural", "agents_launch_neural", "Launch a neural-advisory agent through the API", request_fields=("goal", "backend")),
    EndpointSpec("POST", "/marketplace/tasks", "marketplace_task_create", "Create a local marketplace task", request_fields=("title", "reward", "requester", "metadata")),
    EndpointSpec("POST", "/marketplace/bids", "marketplace_bid_create", "Create a local marketplace bid", request_fields=("task_id", "agent_did", "price")),
    EndpointSpec("POST", "/marketplace/settle", "marketplace_settle", "Settle a local marketplace task"),
    EndpointSpec("GET", "/reputation/{did}", "reputation_lookup", "Look up DID-bound reputation"),
    EndpointSpec("POST", "/attestations", "attestation_create", "Record a local attestation"),
    EndpointSpec("GET", "/audit", "audit_log", "Read local API audit events"),
    EndpointSpec("GET", "/swarm/agents", "swarm_agents", "List local swarm agents"),
    EndpointSpec("POST", "/swarm/delegate", "swarm_delegate", "Create and assign a local delegation contract", request_fields=("delegator_did", "delegate_did", "capability", "objective", "budget", "constraints")),
    EndpointSpec("POST", "/verification/submit", "verification_submit_alias", "Submit a verification result"),
    EndpointSpec("POST", "/verification/{contract_id}", "verification_submit", "Submit completion and optional verification for a delegation", request_fields=("result", "accepted", "evidence")),
    EndpointSpec("GET", "/verification/result", "verification_result_alias", "Get the latest verification result"),
    EndpointSpec("GET", "/verification/{contract_id}", "verification_result", "Get delegation verification status"),
    EndpointSpec("GET", "/manifest", "manifest", "List router endpoints"),
    EndpointSpec("POST", "/flowlang/compile", "flowlang_compile", "Compile FlowLang source to FlowIR manifest", request_fields=("source",)),
    EndpointSpec("POST", "/flowlang/validate", "flowlang_validate", "Validate FlowLang source", request_fields=("source",)),
    EndpointSpec("POST", "/flowlang/run", "flowlang_run", "Run a FlowLang-declared agent", request_fields=("source", "prompt")),
    EndpointSpec("GET", "/flowlang/examples", "flowlang_examples", "Return bundled FlowLang examples"),
    EndpointSpec("POST", "/marketplace/assign", "marketplace_assign", "Assign a marketplace task"),
    EndpointSpec("POST", "/marketplace/submit", "marketplace_submit", "Submit marketplace work"),
    EndpointSpec("POST", "/marketplace/verify", "marketplace_verify", "Verify marketplace work"),
    EndpointSpec("POST", "/marketplace/dispute", "marketplace_dispute", "Open marketplace dispute"),
    EndpointSpec("GET", "/neural/status", "neural_status", "Return neural subsystem status"),
    EndpointSpec("GET", "/neural/backends", "neural_backends", "List neural backend metadata"),
    EndpointSpec("GET", "/neural/gpu-runs", "neural_gpu_runs", "List imported GPU validation runs"),
    EndpointSpec("GET", "/neural/gpu-runs/{run_id}", "neural_gpu_run", "Get imported GPU validation run summary"),
    EndpointSpec("GET", "/neural/benchmarks", "neural_benchmarks", "List neural benchmark metadata"),
    EndpointSpec("GET", "/neural/checkpoints", "neural_checkpoints", "List checkpoint metadata without raw weights"),
    EndpointSpec("POST", "/neural/validate-smoke", "neural_validate_smoke", "Return neural validation smoke command/status"),
    EndpointSpec("POST", "/neural/train-smoke", "neural_train_smoke", "Run tiny local neural smoke trainers", request_fields=("out",)),
    EndpointSpec("GET", "/rl/envs", "rl_envs", "List local Flow Arena environments"),
    EndpointSpec("GET", "/rl/benchmarks", "rl_benchmarks", "List local RL benchmark metadata"),
    EndpointSpec("POST", "/rl/evaluate", "rl_evaluate", "Evaluate a local RL policy", request_fields=("env_id", "policy", "episodes")),
    EndpointSpec("POST", "/rl/train-smoke", "rl_train_smoke", "Run local tabular Q smoke training", request_fields=("env_id", "episodes")),
    EndpointSpec("POST", "/network/run-scenario", "network_run_scenario", "Run a local network scenario", request_fields=("scenario",)),
    EndpointSpec("GET", "/release/evidence", "release_evidence", "Return local release evidence bundle metadata"),
    EndpointSpec("GET", "/release/decision/{target}", "release_decision", "Return local release readiness decision for a target"),
    EndpointSpec("GET", "/dashboard/snapshot", "dashboard_snapshot", "Return local dashboard mock snapshot metadata"),
    EndpointSpec("GET", "/visual/state", "visual_state", "Return current Mission Control visual state"),
    EndpointSpec("GET", "/visual/events", "visual_events", "Return recent Mission Control visual events"),
    EndpointSpec("GET", "/visual/schema", "visual_schema", "Return Mission Control visual telemetry schema"),
    EndpointSpec("GET", "/visual/replay/{run_id}", "visual_replay", "Return a saved visual replay snapshot"),
    EndpointSpec("GET", "/network/state", "network_state", "Return current local network state with visual projection"),
    EndpointSpec("POST", "/visual/replay/start", "visual_replay_start", "Run a local visual replay scenario", request_fields=("scenario", "run_id")),
    EndpointSpec("POST", "/compute/plan", "compute_plan", "Build a Flow Memory Compute Market plan", request_fields=("task", "profile", "agent_id", "goal_id", "request_id", "idempotency_key", "budget_policy", "market_policy", "selection_strategy", "provider_constraints", "network_preferences", "payment_asset_preferences", "dry_run"), response_fields=("ok", "compute_plan", "request_id")),
    EndpointSpec("POST", "/compute/marketplace-plan", "compute_marketplace_plan", "Build a marketplace-only compute plan", request_fields=("task", "profile", "budget_policy", "market_policy", "selection_strategy"), response_fields=("ok", "compute_plan")),
    EndpointSpec("POST", "/compute/quote", "compute_quote", "Collect normalized compute quotes", request_fields=("task", "profile", "scenario", "budget_policy", "market_policy", "request_id"), response_fields=("ok", "profile", "quotes", "request_id")),
    EndpointSpec("POST", "/compute/route", "compute_route", "Select a compute route under policy", request_fields=("task", "profile", "budget_policy", "market_policy", "selection_strategy"), response_fields=("ok", "route_decision")),
    EndpointSpec("POST", "/compute/payment-plan", "compute_payment_plan", "Build a dry-run compute payment plan", request_fields=("task", "profile", "budget_policy", "market_policy", "selection_strategy"), response_fields=("ok", "payment_plan", "settlement_intent", "dry_run_only")),
    EndpointSpec("POST", "/compute/simulate-settlement", "compute_simulate_settlement", "Simulate dry-run compute settlement", request_fields=("task", "profile", "budget_policy", "market_policy"), response_fields=("ok", "settlement_intent", "payment_plan", "dry_run_only")),
    EndpointSpec("GET", "/compute/providers", "compute_providers", "List compute provider metadata", response_fields=("ok", "providers", "registry", "next_cursor")),
    EndpointSpec("GET", "/compute/providers/{provider_id}", "compute_provider", "Get a compute provider", response_fields=("ok", "provider")),
    EndpointSpec("POST", "/compute/providers", "compute_provider_create", "Create a compute provider", request_fields=("provider_id", "provider_name", "provider_type", "status"), response_fields=("ok", "provider")),
    EndpointSpec("PATCH", "/compute/providers/{provider_id}", "compute_provider_update", "Update a compute provider", request_fields=("status", "capabilities"), response_fields=("ok", "provider")),
    EndpointSpec("POST", "/compute/providers/{provider_id}/disable", "compute_provider_disable", "Disable a compute provider", response_fields=("ok", "provider")),
    EndpointSpec("POST", "/compute/providers/{provider_id}/health-check", "compute_provider_health", "Run a provider health check", response_fields=("ok", "provider_health")),
    EndpointSpec("POST", "/compute/providers/external/quote", "compute_provider_external_quote", "Request a dry-run live quote from an explicitly allowlisted external provider endpoint", request_fields=("provider_id", "task", "profile", "allowed_assets", "allowed_networks"), response_fields=("ok", "provider_id", "quotes", "raw_quotes")),
    EndpointSpec("GET", "/compute/routes", "compute_routes", "List compute routes", response_fields=("ok", "routes", "next_cursor")),
    EndpointSpec("GET", "/compute/routes/{route_id}", "compute_route_get", "Get a compute route", response_fields=("ok", "route")),
    EndpointSpec("POST", "/compute/routes", "compute_route_create", "Create a compute route", request_fields=("route_id", "provider_id", "unit_type", "pricing_model"), response_fields=("ok", "route")),
    EndpointSpec("PATCH", "/compute/routes/{route_id}", "compute_route_update", "Update a compute route", request_fields=("enabled", "capacity_window"), response_fields=("ok", "route")),
    EndpointSpec("POST", "/compute/routes/{route_id}/disable", "compute_route_disable", "Disable a compute route", response_fields=("ok", "route")),
    EndpointSpec("GET", "/compute/policies", "compute_policies", "Return compute policies and simulation scenarios", response_fields=("ok", "policies", "default_market_policy", "selection_strategies", "simulation_scenarios")),
    EndpointSpec("GET", "/compute/policies/{policy_id}", "compute_policy", "Get a compute policy", response_fields=("ok", "policy")),
    EndpointSpec("POST", "/compute/policies", "compute_policy_create", "Create a compute policy", request_fields=("policy_id", "max_total_cost", "dry_run_required"), response_fields=("ok", "policy")),
    EndpointSpec("PATCH", "/compute/policies/{policy_id}", "compute_policy_update", "Update a compute policy", response_fields=("ok", "policy")),
    EndpointSpec("POST", "/compute/policies/{policy_id}/validate", "compute_policy_validate", "Validate a compute policy", response_fields=("ok", "validation")),
    EndpointSpec("GET", "/compute/economic-memory", "compute_economic_memory", "Return durable compute economic memory", response_fields=("ok", "schema_fields", "records", "next_cursor")),
    EndpointSpec("POST", "/compute/economic-memory/query", "compute_economic_memory_query", "Query durable compute economic memory", request_fields=("query", "agent_id", "goal_id", "provider_id", "route_id", "task_type", "limit", "cursor"), response_fields=("ok", "query", "data", "confidence", "sample_size")),
    EndpointSpec("GET", "/compute/economic-memory/summary", "compute_economic_memory_summary", "Summarize compute economic memory", response_fields=("ok", "data", "confidence")),
    EndpointSpec("GET", "/compute/economic-memory/anomalies", "compute_economic_memory_anomalies", "List compute economic memory anomalies", response_fields=("ok", "data", "warnings")),
    EndpointSpec("GET", "/compute/economic-memory/providers/{provider_id}", "compute_economic_memory_provider", "Summarize provider economic memory", response_fields=("ok", "data")),
    EndpointSpec("GET", "/compute/economic-memory/routes/{route_id}", "compute_economic_memory_route", "Summarize route economic memory", response_fields=("ok", "data")),
    EndpointSpec("GET", "/compute/economic-memory/tasks/{task_type}", "compute_economic_memory_task", "Summarize task-type economic memory", response_fields=("ok", "data")),
    EndpointSpec("GET", "/compute/decisions/{decision_id}", "compute_decision", "Get a route decision", response_fields=("ok", "route_decision")),
    EndpointSpec("POST", "/compute/decisions/{decision_id}/replay", "compute_decision_replay", "Replay a compute route decision without mutating the original", response_fields=("ok", "original_decision", "current_decision", "differences")),
    EndpointSpec("GET", "/compute/audit", "compute_audit", "List compute audit events", response_fields=("ok", "audit_events", "next_cursor")),
    EndpointSpec("GET", "/compute/audit/verify", "compute_audit_verify", "Verify tamper-evident compute audit hash chains", response_fields=("ok", "audit_chain")),
    EndpointSpec("POST", "/compute/audit/export", "compute_audit_export", "Export compute audit events with a checkpoint", request_fields=("chain_id", "out", "from_sequence", "to_sequence"), response_fields=("ok", "checkpoint", "manifest_hash")),
    EndpointSpec("POST", "/compute/audit/checkpoint", "compute_audit_checkpoint", "Create a compute audit checkpoint", request_fields=("chain_id",), response_fields=("ok", "checkpoint")),
    EndpointSpec("POST", "/compute/audit/verify-export", "compute_audit_verify_export", "Verify an exported compute audit checkpoint", request_fields=("path",), response_fields=("ok", "checkpoint_hash", "event_count")),
    EndpointSpec("GET", "/compute/audit/{audit_event_id}", "compute_audit_event", "Get a compute audit event", response_fields=("ok", "audit_event")),
    EndpointSpec("POST", "/compute/jobs", "compute_job_create", "Create a dry-run compute job record and lifecycle event", request_fields=("task_type", "input_ref", "model_or_runtime", "resource_request", "budget_policy_id", "route_id", "provider_id"), response_fields=("ok", "job", "event")),
    EndpointSpec("GET", "/compute/jobs/{job_id}", "compute_job", "Get a compute job", response_fields=("ok", "job")),
    EndpointSpec("POST", "/compute/jobs/{job_id}/cancel", "compute_job_cancel", "Cancel a queued compute job", response_fields=("ok", "job", "event")),
    EndpointSpec("GET", "/compute/jobs/{job_id}/events", "compute_job_events", "List compute job events", response_fields=("ok", "events")),
    EndpointSpec("GET", "/compute/jobs/{job_id}/artifacts", "compute_job_artifacts", "List compute job artifacts", response_fields=("ok", "artifacts")),
    EndpointSpec("POST", "/compute/jobs/{job_id}/retry", "compute_job_retry", "Queue a compute job retry", response_fields=("ok", "job", "event")),
    EndpointSpec("POST", "/compute/jobs/{job_id}/dispatch", "compute_job_dispatch", "Dispatch a queued dry-run compute job into running state", response_fields=("ok", "job", "event")),
    EndpointSpec("POST", "/compute/jobs/{job_id}/complete", "compute_job_complete", "Complete a running dry-run compute job, record artifacts, and record usage", request_fields=("artifact_data", "artifact_ref", "actual_units", "actual_total_cost", "currency"), response_fields=("ok", "job", "event", "artifact", "usage_charge")),
    EndpointSpec("POST", "/compute/jobs/{job_id}/fail", "compute_job_fail", "Fail a queued or running dry-run compute job with structured error details", request_fields=("error_code", "reason"), response_fields=("ok", "job", "event")),
    EndpointSpec("POST", "/market/providers/apply", "market_provider_apply", "Submit provider onboarding application with external secret references only", request_fields=("provider_id", "provider_name", "provider_type", "supported_unit_types", "supported_assets", "supported_networks", "quote_endpoint", "health_endpoint", "credentials", "sla"), response_fields=("ok", "provider_application", "credential_storage")),
    EndpointSpec("GET", "/market/providers/{provider_id}", "market_provider", "Get provider application, provider metadata, and reputation", response_fields=("ok", "provider_application", "provider", "reputation")),
    EndpointSpec("POST", "/market/providers/{provider_id}/verify", "market_provider_verify", "Verify a provider application for dry-run marketplace participation", response_fields=("ok", "provider_application", "provider", "reputation")),
    EndpointSpec("POST", "/market/providers/{provider_id}/conformance", "market_provider_conformance", "Validate a provider sandbox quote against the provider contract and optional signature", request_fields=("sample_quote", "allowed_assets", "allowed_networks", "public_key"), response_fields=("ok", "validation", "signed_quote_valid", "conformance")),
    EndpointSpec("POST", "/market/providers/{provider_id}/disable", "market_provider_disable", "Disable a market provider", response_fields=("ok", "provider_application")),
    EndpointSpec("GET", "/market/providers/{provider_id}/reputation", "market_provider_reputation", "Get provider reputation metrics", response_fields=("ok", "reputation")),
    EndpointSpec("POST", "/market/quotes/ingest", "market_quote_ingest", "Validate, replay-protect, cache, and audit a live provider quote", request_fields=("quote", "allowed_assets", "allowed_networks"), response_fields=("ok", "quote", "validation", "drift")),
    EndpointSpec("POST", "/market/capacity/list", "market_capacity_list", "List provider capacity into the reservation book", request_fields=("provider_id", "route_id", "resource_type", "gpu_type", "available_units", "starts_at", "ends_at", "price_floor"), response_fields=("ok", "capacity_window")),
    EndpointSpec("POST", "/market/capacity/reserve", "market_capacity_reserve", "Hold capacity without moving funds", request_fields=("provider_id", "route_id", "capacity_units"), response_fields=("ok", "reservation")),
    EndpointSpec("POST", "/market/capacity/release", "market_capacity_release", "Release held capacity", request_fields=("reservation_id",), response_fields=("ok", "reservation")),
    EndpointSpec("GET", "/market/capacity/order-book", "market_capacity_order_book", "Return capacity windows and reservations", response_fields=("ok", "capacity_windows", "reservations", "summary")),
    EndpointSpec("GET", "/market/prices", "market_prices", "List ingested compute prices", response_fields=("ok", "prices")),
    EndpointSpec("GET", "/market/prices/history", "market_prices_history", "List compute price history", response_fields=("ok", "prices")),
    EndpointSpec("POST", "/billing/checkout", "billing_checkout", "Create a no-custody external checkout request", request_fields=("account_id", "amount", "currency", "provider"), response_fields=("ok", "checkout", "next_safe_actions")),
    EndpointSpec("POST", "/billing/webhooks/stripe", "billing_webhook_stripe", "Verify and store a Stripe webhook event envelope", request_fields=("raw_event", "stripe_signature"), response_fields=("ok", "payment_event")),
    EndpointSpec("GET", "/billing/balance", "billing_balance", "Get credit balance ledger state", response_fields=("ok", "balance")),
    EndpointSpec("GET", "/billing/usage", "billing_usage", "List usage charges", response_fields=("ok", "usage_charges")),
    EndpointSpec("GET", "/admin/reconciliation", "admin_reconciliation", "Run dry-run reconciliation count checks", response_fields=("ok", "reconciliation")),
    EndpointSpec("GET", "/admin/storage/diagnostics", "admin_storage_diagnostics", "Verify managed SQL migrations, required tables, indexes, advisory lock access, and audit chain state", response_fields=("ok", "storage", "migration_status", "migration_history", "schema_verification", "production_readiness", "audit_chain")),
    EndpointSpec("GET", "/admin/redis/diagnostics", "admin_redis_diagnostics", "Verify managed Redis limiter and circuit-breaker probes through the active production backend", response_fields=("ok", "rate_limiter", "circuit_breaker", "rate_limit_probe", "circuit_breaker_probe")),
    EndpointSpec("GET", "/compute/health", "compute_health", "Compute Market health check", response_fields=("ok", "compute_market_enabled", "database_reachable", "audit_log_writable")),
    EndpointSpec("GET", "/compute/readiness", "compute_readiness", "Compute Market production readiness check", response_fields=("ok", "migration_plan", "production_safety_defaults")),
    EndpointSpec("GET", "/compute/telemetry", "compute_telemetry", "Return Compute Market telemetry samples and summary", response_fields=("ok", "telemetry", "summary")),
    EndpointSpec("GET", "/compute/metrics", "compute_metrics", "Return Compute Market Prometheus-format metrics text", response_fields=("ok", "content_type", "metrics")),
    EndpointSpec("GET", "/compute/alerts", "compute_alerts", "Evaluate Compute Market alert rules against in-process telemetry", response_fields=("ok", "alerts", "acknowledgements")),
    EndpointSpec("POST", "/compute/alerts/{rule_name}/ack", "compute_alert_ack", "Acknowledge a firing Compute Market alert rule", request_fields=("acknowledged_by",), response_fields=("ok", "acknowledgement")),
)


def endpoint_manifest() -> Mapping[str, Any]:
    return {"endpoints": tuple(endpoint.as_record() for endpoint in API_ENDPOINTS)}
