"""API endpoint manifest for the dependency-free local router."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence


@dataclass(frozen=True)
class EndpointSpec:
    method: str
    path: str
    name: str
    description: str
    request_fields: Sequence[str] = field(default_factory=tuple)
    response_fields: Sequence[str] = field(default_factory=tuple)

    def as_record(self) -> Mapping[str, Any]:
        return {
            "method": self.method,
            "path": self.path,
            "name": self.name,
            "description": self.description,
            "request_fields": tuple(self.request_fields),
            "response_fields": tuple(self.response_fields),
        }


API_ENDPOINTS: tuple[EndpointSpec, ...] = (
    EndpointSpec("GET", "/health", "health", "Router health check", response_fields=("ok", "service")),
    EndpointSpec("GET", "/runtime/status", "runtime_status", "Local runtime status"),
    EndpointSpec("POST", "/runtime/tick", "runtime_tick", "Advance local runtime tick"),
    EndpointSpec("GET", "/agents", "agents_list", "List registered agent cards"),
    EndpointSpec("GET", "/agents/{did}", "agents_get", "Get a registered agent card"),
    EndpointSpec("GET", "/agents/{did}/memory", "agent_memory", "Get local memory records for an agent"),
    EndpointSpec("GET", "/agents/{did}/skills", "agent_skills", "Get skills associated with an agent"),
    EndpointSpec("POST", "/agents/{did}/run", "agent_run", "Run a local agent cycle placeholder"),
    EndpointSpec("POST", "/agents/launch", "agents_launch", "Launch a local agent through the API", request_fields=("goal", "name", "identity", "autonomy_mode")),
    EndpointSpec("POST", "/agents/launch-flowlang", "agents_launch_flowlang", "Launch a FlowLang-declared agent through the API", request_fields=("source", "goal")),
    EndpointSpec("POST", "/agents/launch-neural", "agents_launch_neural", "Launch a neural-advisory agent through the API", request_fields=("goal", "backend")),
    EndpointSpec("POST", "/launch/agent", "launch_agent", "Run the Live Agent Launchpad workflow", request_fields=("template", "ticks", "neural", "emit_visual"), response_fields=("summary", "events", "state")),
    EndpointSpec("POST", "/launch/agent/from-flow", "launch_agent_from_flow", "Run the Live Agent Launchpad workflow from FlowLang source", request_fields=("source", "ticks", "neural", "emit_visual"), response_fields=("summary", "events", "state")),
    EndpointSpec("GET", "/launch/runs", "launch_runs_list", "List local Live Agent Launchpad run records", response_fields=("runs",)),
    EndpointSpec("GET", "/launch/runs/{run_id}", "launch_run_get", "Inspect one local Live Agent Launchpad run record", response_fields=("run",)),
    EndpointSpec("POST", "/launch/runs/{run_id}/replay", "launch_run_replay", "Return replay metadata for a local Live Agent Launchpad run", response_fields=("run", "replay_artifact_path", "summary")),
    EndpointSpec("POST", "/launch/runs/{run_id}/export", "launch_run_export", "Export a lightweight local run bundle", request_fields=("out",), response_fields=("bundle_path", "record")),
    EndpointSpec("POST", "/launch/runs/{run_id}/stop", "launch_run_stop", "Stop or no-op a local Live Agent Launchpad run", response_fields=("status_before", "status_after", "noop")),
    EndpointSpec("POST", "/launch/supervisor/start", "launch_supervisor_start", "Start a bounded local Live Agent Supervisor run", request_fields=("template", "ticks", "tick_interval_ms", "neural", "emit_visual"), response_fields=("supervisor", "heartbeat", "run")),
    EndpointSpec("GET", "/launch/supervisor/status", "launch_supervisor_status", "Inspect local Live Agent Supervisor status", response_fields=("runs", "latest_run_id")),
    EndpointSpec("GET", "/launch/supervisor/runs/{run_id}", "launch_supervisor_get", "Inspect one local Live Agent Supervisor run", response_fields=("supervisor",)),
    EndpointSpec("GET", "/launch/supervisor/runs/{run_id}/heartbeat", "launch_supervisor_heartbeat", "Inspect heartbeat metadata for a supervised run", response_fields=("heartbeat",)),
    EndpointSpec("POST", "/launch/supervisor/runs/{run_id}/pause", "launch_supervisor_pause", "Pause a non-terminal supervised run or return a terminal no-op", response_fields=("status_before", "status_after", "noop")),
    EndpointSpec("POST", "/launch/supervisor/runs/{run_id}/resume", "launch_supervisor_resume", "Create a continuation run from supervised metadata", request_fields=("ticks", "emit_visual"), response_fields=("supervisor", "continued_from_run_id")),
    EndpointSpec("POST", "/launch/supervisor/runs/{run_id}/stop", "launch_supervisor_stop", "Stop a non-terminal supervised run or return a terminal no-op", response_fields=("status_before", "status_after", "noop")),
    EndpointSpec("GET", "/launch/console/runs", "launch_console_runs", "List Mission Control run console summaries", response_fields=("runs", "fixtures")),
    EndpointSpec("GET", "/launch/console/runs/{run_id}", "launch_console_run", "Inspect one Mission Control run console summary", response_fields=("run", "source")),
    EndpointSpec("GET", "/launch/console/fixtures", "launch_console_fixtures", "List Mission Control replay/demo fixtures", response_fields=("fixtures",)),
    EndpointSpec("POST", "/launch/bundles/public-alpha", "launch_bundle_public_alpha", "Build a local public-alpha demo bundle", request_fields=("out",), response_fields=("bundle_path", "mission_control_fixtures", "commands")),
    EndpointSpec("GET", "/launch/console/runs/{run_id}/embodiment", "launch_console_run_embodiment", "Return the 3D-ready neural embodiment state for a Mission Control run", response_fields=("embodiment", "graph", "events")),
    EndpointSpec("POST", "/launch/finalize/public-alpha", "launch_finalize_public_alpha", "Finalize local public-alpha handoff evidence", request_fields=("out",), response_fields=("finalizer_path", "mission_control_live_3d", "release_decisions")),
    EndpointSpec("POST", "/cognition/predict", "cognition_predict", "Predict candidate outcomes without executing actions", request_fields=("goal", "action", "agent_id"), response_fields=("state", "candidate_actions", "predictions", "counterfactuals", "scores")),
    EndpointSpec("POST", "/cognition/tick", "cognition_tick", "Run one local prediction-driven cognition tick", request_fields=("goal", "agent", "action", "actual_outcome"), response_fields=("prediction", "prediction_error", "experience", "learning_update")),
    EndpointSpec("GET", "/cognition/experiences", "cognition_experiences", "List local predictive cognition experience records", response_fields=("experiences",)),
    EndpointSpec("GET", "/cognition/experiences/{experience_id}", "cognition_experience", "Inspect one local predictive cognition experience record", response_fields=("experience",)),
    EndpointSpec("GET", "/cognition/prediction-errors", "cognition_prediction_errors", "List prediction-error records from local experiences", response_fields=("prediction_errors",)),
    EndpointSpec("POST", "/cognition/memory/query", "cognition_memory_query", "Query local predictive cognition experience memory", request_fields=("query", "agent_id", "tags"), response_fields=("experiences",)),
    EndpointSpec("POST", "/cognition/benchmarks/run", "cognition_benchmark_run", "Run deterministic predictive learning benchmark scenarios", request_fields=("scenario", "trials"), response_fields=("metrics", "scenario_results", "consolidated_lessons")),
    EndpointSpec("GET", "/cognition/benchmarks", "cognition_benchmarks", "List local predictive learning benchmark records", response_fields=("benchmarks", "latest_metrics")),
    EndpointSpec("GET", "/cognition/benchmarks/{benchmark_id}", "cognition_benchmark", "Inspect one predictive learning benchmark record", response_fields=("benchmark",)),
    EndpointSpec("POST", "/cognition/lessons/consolidate", "cognition_lessons_consolidate", "Consolidate prediction-error experiences into reusable lessons", request_fields=("min_repetitions",), response_fields=("lessons", "consolidated_lesson_count")),
    EndpointSpec("GET", "/cognition/lessons", "cognition_lessons", "List consolidated predictive cognition lessons", response_fields=("lessons",)),
    EndpointSpec("GET", "/cognition/lessons/{lesson_id}", "cognition_lesson", "Inspect one consolidated predictive cognition lesson", response_fields=("lesson",)),
    EndpointSpec("GET", "/cognition/metrics", "cognition_metrics", "Return aggregate predictive cognition learning metrics", response_fields=("prediction_accuracy_after", "prediction_error_mean_after", "lesson_reuse_rate")),
    EndpointSpec("GET", "/launch/console/runs/{run_id}/predictions", "launch_console_run_predictions", "Return predictive cognition records associated with a Mission Control run", response_fields=("predictions", "experiences")),
    EndpointSpec("GET", "/visual/embodiment/{run_id}/cognition", "visual_embodiment_cognition", "Return neural embodiment plus predictive cognition projection for a run", response_fields=("embodiment", "cognition")),
    EndpointSpec("GET", "/genesis/archetypes", "genesis_archetypes", "List Agent Genesis archetypes", response_fields=("archetypes",)),
    EndpointSpec("GET", "/genesis/instincts", "genesis_instincts", "List Agent Genesis instincts", response_fields=("instincts",)),
    EndpointSpec("GET", "/genesis/boundaries", "genesis_boundaries", "List Agent Genesis boundary rules", response_fields=("boundaries",)),
    EndpointSpec("POST", "/genesis/birth", "genesis_birth", "Birth a policy-gated Flow Memory agent", request_fields=("user_id", "name", "archetype", "purpose", "instincts", "boundaries", "consent_mode"), response_fields=("birth_certificate", "first_prediction", "passport", "mirror")),
    EndpointSpec("GET", "/genesis/agents/{agent_id}/passport", "genesis_passport", "Inspect an Agent Genesis passport", response_fields=("passport",)),
    EndpointSpec("GET", "/genesis/agents/{agent_id}/genome", "genesis_genome", "Inspect an Agent Genome", response_fields=("genome",)),
    EndpointSpec("GET", "/genesis/agents/{agent_id}/mirror", "genesis_mirror", "Inspect an Agent Mirror", response_fields=("mirror",)),
    EndpointSpec("POST", "/genesis/agents/{agent_id}/teaching", "genesis_teaching", "Record a private-by-default human teaching event", request_fields=("lesson", "correction_type", "tags"), response_fields=("private_lesson",)),
    EndpointSpec("GET", "/genesis/contributions", "genesis_contributions", "List sanitized network contributions", response_fields=("contributions",)),
    EndpointSpec("POST", "/genesis/contributions/export", "genesis_contributions_export", "Export sanitized network contribution bundle", request_fields=("agent_id", "out"), response_fields=("contributions", "path")),
    EndpointSpec("GET", "/internet/agents", "internet_agents", "List local Agent Internet identities", response_fields=("agents", "count")),
    EndpointSpec("POST", "/internet/agents/register", "internet_agents_register", "Register a local Agent Internet identity", request_fields=("agent_id", "display_name", "genome_id"), response_fields=("network_agent_id", "privacy_policy", "contribution_policy")),
    EndpointSpec("GET", "/internet/agents/{agent_id}", "internet_agent", "Inspect one local Agent Internet identity", response_fields=("agent",)),
    EndpointSpec("POST", "/internet/skills/publish", "internet_skills_publish", "Publish a policy-gated skill manifest", request_fields=("agent_id", "skills", "domains"), response_fields=("manifest_id", "skills", "safety_constraints")),
    EndpointSpec("POST", "/internet/skills/match", "internet_skills_match", "Rank collaborators by skill, reputation, privacy, and policy compatibility", request_fields=("agent_id", "task", "required_skills", "optional_skills"), response_fields=("ranked_candidates", "recommended_collaborator_ids", "policy_warnings")),
    EndpointSpec("POST", "/internet/collaborations/propose", "internet_collaborations_propose", "Create a local policy-gated collaboration proposal", request_fields=("from_agent_id", "to_agent_id", "task", "required_skills"), response_fields=("request", "session", "workspace", "project_graph")),
    EndpointSpec("GET", "/internet/collaborations", "internet_collaborations", "List local Agent Internet collaboration sessions", response_fields=("collaborations", "count")),
    EndpointSpec("GET", "/internet/collaborations/{session_id}", "internet_collaboration", "Inspect one local Agent Internet collaboration session", response_fields=("collaboration",)),
    EndpointSpec("GET", "/internet/workspaces/{workspace_id}", "internet_workspace", "Inspect a structured shared cognitive workspace", response_fields=("workspace",)),
    EndpointSpec("GET", "/internet/reputation/{agent_id}", "internet_reputation", "Inspect local prediction-quality based Agent Internet reputation", response_fields=("reputation",)),
    EndpointSpec("POST", "/internet/payment-intents/simulate", "internet_payment_intent_simulate", "Simulate an x402-style dry-run payment intent without funds or broadcast", request_fields=("from_agent_id", "to_agent_id", "resource", "amount"), response_fields=("intent_id", "rail", "settlement_state", "no_funds_moved")),
    EndpointSpec("GET", "/internet/erc8004/{agent_id}", "internet_erc8004", "Export ERC-8004-style identity, reputation, and validation adapter data without on-chain calls", response_fields=("path", "export")),
    EndpointSpec("GET", "/internet/mcp/manifests", "internet_mcp_manifests", "List local policy-gated MCP-style tool manifests", response_fields=("manifests", "count")),
    EndpointSpec("GET", "/byok/providers", "byok_providers", "List optional BYOK provider metadata without external calls", response_fields=("providers", "count")),
    EndpointSpec("POST", "/byok/credentials", "byok_credentials_create", "Bind a redacted provider credential reference to an existing agent", request_fields=("agent_id", "provider", "secret_ref"), response_fields=("credential_id", "secret_fingerprint", "raw_secret_persisted")),
    EndpointSpec("GET", "/byok/credentials", "byok_credentials", "List redacted credential bindings", response_fields=("credentials", "count")),
    EndpointSpec("GET", "/byok/credentials/{credential_id}", "byok_credential", "Inspect one redacted credential binding", response_fields=("credential",)),
    EndpointSpec("POST", "/byok/credentials/{credential_id}/revoke", "byok_credential_revoke", "Revoke a credential reference", response_fields=("credential_id", "status", "revoked_at")),
    EndpointSpec("POST", "/byok/intents/simulate", "byok_intent_simulate", "Simulate a BYOK inference intent without provider calls", request_fields=("agent_id", "provider", "model", "purpose"), response_fields=("intent_id", "status", "no_external_call_performed")),
    EndpointSpec("POST", "/wallet/bindings", "wallet_bindings_create", "Bind an address-only wallet identity stub to an existing agent", request_fields=("agent_id", "network", "address"), response_fields=("wallet_binding_id", "network_name", "no_private_key_required")),
    EndpointSpec("GET", "/wallet/bindings", "wallet_bindings", "List wallet identity bindings", response_fields=("wallet_bindings", "count")),
    EndpointSpec("GET", "/wallet/bindings/{wallet_binding_id}", "wallet_binding", "Inspect one wallet identity binding", response_fields=("wallet_binding",)),
    EndpointSpec("POST", "/onchain/upgrades/prepare", "onchain_upgrade_prepare", "Prepare an on-chain dry-run upgrade intent and typed-data metadata", request_fields=("agent_id", "network", "action"), response_fields=("intent_id", "eip712_typed_data", "approval_record_id")),
    EndpointSpec("POST", "/onchain/upgrades/{intent_id}/simulate", "onchain_upgrade_simulate", "Simulate an on-chain upgrade intent without broadcast", response_fields=("simulation_result", "no_broadcast")),
    EndpointSpec("POST", "/onchain/upgrades/{intent_id}/approve", "onchain_upgrade_approve", "Record human approval metadata for a dry-run upgrade", response_fields=("approval", "intent")),
    EndpointSpec("POST", "/onchain/upgrades/{intent_id}/sign-request", "onchain_upgrade_sign_request", "Return external signing instructions without signing", response_fields=("typed_data", "no_private_key_required")),
    EndpointSpec("POST", "/onchain/upgrades/{intent_id}/relay", "onchain_upgrade_relay", "Return relay blocked/dry-run-only status by default", response_fields=("blocked", "relay_status", "no_broadcast")),
    EndpointSpec("POST", "/emergency-stop", "emergency_stop_create", "Activate an emergency stop for optional upgrades", request_fields=("agent_id", "scope", "reason"), response_fields=("emergency_stop", "disabled_capabilities")),
    EndpointSpec("GET", "/emergency-stop/{agent_id}", "emergency_stop_agent", "Inspect emergency stop status for an agent", response_fields=("active", "stops")),
    EndpointSpec("GET", "/x402/status", "x402_status", "Inspect installed x402 SDK readiness and Coinbase facilitator metadata", response_fields=("installed", "recommended_install", "coinbase_facilitator_url")),
    EndpointSpec("POST", "/x402/routes/prepare", "x402_route_prepare", "Prepare a testnet-ready x402 payment route without relay or broadcast by default", request_fields=("agent_id", "resource", "price", "pay_to"), response_fields=("route_id", "payment_requirements_preview", "settlement_enabled")),
    EndpointSpec("GET", "/agent-builder/defaults", "agent_builder_defaults", "Return Agent Builder browser defaults for first-agent creation and optional capability composition", response_fields=("archetypes", "capability_cards", "first_agent_requires_wallet")),
    EndpointSpec("POST", "/agent-builder/assembly-plan", "agent_builder_assembly_plan", "Create a local Agent Builder agent assembly plan", request_fields=("name", "archetype", "purpose"), response_fields=("agent_builder_id", "plan")),
    EndpointSpec("POST", "/agent-builder/birth", "agent_builder_birth", "Birth an agent through Agent Builder and return Mission Control handoff metadata", request_fields=("name", "archetype", "purpose", "instincts", "boundaries"), response_fields=("birth", "plan", "mission_control_url")),
    EndpointSpec("POST", "/agent-builder/simulate-upgrades", "agent_builder_simulate_upgrades", "Simulate optional post-birth Agent Builder capability upgrades without funds or broadcast", request_fields=("agent_id", "byok", "wallet", "onchain_dry_run"), response_fields=("requested", "capability_summary", "no_broadcast")),
    EndpointSpec("POST", "/experience-graph/build", "experience_graph_build", "Build the local Experience Graph plus Proof of Learning ledger", request_fields=("write_artifacts",), response_fields=("graph", "proof_ledger", "reputation")),
    EndpointSpec("GET", "/experience-graph", "experience_graph_latest", "Inspect the latest local Experience Graph", response_fields=("graph", "metrics")),
    EndpointSpec("GET", "/experience-graph/{graph_id}", "experience_graph_get", "Inspect one Experience Graph artifact", response_fields=("graph",)),
    EndpointSpec("GET", "/experience-graph/agents/{agent_id}", "experience_graph_agent", "Inspect one agent's subgraph", response_fields=("nodes", "edges", "proofs")),
    EndpointSpec("GET", "/proof-of-learning", "proof_of_learning_records", "List local Proof of Learning records", response_fields=("proofs",)),
    EndpointSpec("GET", "/proof-of-learning/{proof_id}", "proof_of_learning_record", "Inspect one Proof of Learning record", response_fields=("proof",)),
    EndpointSpec("GET", "/learning-reputation", "learning_reputations", "List prediction-quality based agent reputations", response_fields=("reputations",)),
    EndpointSpec("GET", "/learning-reputation/{agent_id}", "learning_reputation", "Inspect one agent's learning reputation", response_fields=("reputation",)),
    EndpointSpec("GET", "/visual/embodiment/{run_id}", "visual_embodiment", "Return the Mission Control neural embodiment projection for a run", response_fields=("embodiment", "graph", "events")),
    EndpointSpec("POST", "/marketplace/tasks", "marketplace_task_create", "Create a local marketplace task", request_fields=("title", "reward", "requester", "metadata")),
    EndpointSpec("POST", "/marketplace/bids", "marketplace_bid_create", "Create a local marketplace bid", request_fields=("task_id", "agent_did", "price")),
    EndpointSpec("POST", "/marketplace/settle", "marketplace_settle", "Settle a local marketplace task"),
    EndpointSpec("GET", "/reputation/{did}", "reputation_lookup", "Look up DID-bound reputation"),
    EndpointSpec("POST", "/attestations", "attestation_create", "Record a local attestation"),
    EndpointSpec("GET", "/audit", "audit_log", "Read local API audit events"),
    EndpointSpec("GET", "/swarm/agents", "swarm_agents", "List local swarm agents"),
    EndpointSpec("POST", "/swarm/delegate", "swarm_delegate", "Create and assign a local delegation contract", request_fields=("delegator_did", "delegate_did", "capability", "objective", "budget", "constraints")),
    EndpointSpec("POST", "/verification/submit", "verification_submit_alias", "Submit a verification result"),
    EndpointSpec("POST", "/verification/{contract_id}", "verification_submit", "Submit completion and optional verification for a delegation", request_fields=("result", "accepted", "evidence")),
    EndpointSpec("GET", "/verification/result", "verification_result_alias", "Get the latest verification result"),
    EndpointSpec("GET", "/verification/{contract_id}", "verification_result", "Get delegation verification status"),
    EndpointSpec("GET", "/manifest", "manifest", "List router endpoints"),
    EndpointSpec("POST", "/flowlang/compile", "flowlang_compile", "Compile FlowLang source to FlowIR manifest", request_fields=("source",)),
    EndpointSpec("POST", "/flowlang/validate", "flowlang_validate", "Validate FlowLang source", request_fields=("source",)),
    EndpointSpec("POST", "/flowlang/run", "flowlang_run", "Run a FlowLang-declared agent", request_fields=("source", "prompt")),
    EndpointSpec("GET", "/flowlang/examples", "flowlang_examples", "Return bundled FlowLang examples"),
    EndpointSpec("POST", "/marketplace/assign", "marketplace_assign", "Assign a marketplace task"),
    EndpointSpec("POST", "/marketplace/submit", "marketplace_submit", "Submit marketplace work"),
    EndpointSpec("POST", "/marketplace/verify", "marketplace_verify", "Verify marketplace work"),
    EndpointSpec("POST", "/marketplace/dispute", "marketplace_dispute", "Open marketplace dispute"),
    EndpointSpec("GET", "/neural/status", "neural_status", "Return neural subsystem status"),
    EndpointSpec("GET", "/neural/backends", "neural_backends", "List neural backend metadata"),
    EndpointSpec("GET", "/neural/gpu-runs", "neural_gpu_runs", "List imported GPU validation runs"),
    EndpointSpec("GET", "/neural/gpu-runs/{run_id}", "neural_gpu_run", "Get imported GPU validation run summary"),
    EndpointSpec("GET", "/neural/benchmarks", "neural_benchmarks", "List neural benchmark metadata"),
    EndpointSpec("GET", "/neural/checkpoints", "neural_checkpoints", "List checkpoint metadata without raw weights"),
    EndpointSpec("POST", "/neural/validate-smoke", "neural_validate_smoke", "Return neural validation smoke command/status"),
    EndpointSpec("POST", "/neural/train-smoke", "neural_train_smoke", "Run tiny local neural smoke trainers", request_fields=("out",)),
    EndpointSpec("POST", "/neural/live/sessions", "neural_live_create", "Create a local neural live runtime session", request_fields=("agent_id", "config"), response_fields=("session",)),
    EndpointSpec("GET", "/neural/live/sessions", "neural_live_sessions", "List local neural live runtime sessions"),
    EndpointSpec("GET", "/neural/live/sessions/{session_id}", "neural_live_session", "Inspect a local neural live runtime session"),
    EndpointSpec("POST", "/neural/live/sessions/{session_id}/step", "neural_live_step", "Run one deterministic local neural live step", request_fields=("context",)),
    EndpointSpec("POST", "/neural/live/sessions/{session_id}/learn", "neural_live_learn", "Run one deterministic local neural learning update", request_fields=("sample",)),
    EndpointSpec("POST", "/neural/live/sessions/{session_id}/checkpoint", "neural_live_checkpoint", "Write neural checkpoint metadata only", request_fields=("checkpoint_ref",)),
    EndpointSpec("POST", "/neural/live/sessions/{session_id}/stop", "neural_live_stop", "Stop a local neural live runtime session"),
    EndpointSpec("GET", "/rl/envs", "rl_envs", "List local Flow Arena environments"),
    EndpointSpec("GET", "/rl/benchmarks", "rl_benchmarks", "List local RL benchmark metadata"),
    EndpointSpec("POST", "/rl/evaluate", "rl_evaluate", "Evaluate a local RL policy", request_fields=("env_id", "policy", "episodes")),
    EndpointSpec("POST", "/rl/train-smoke", "rl_train_smoke", "Run local tabular Q smoke training", request_fields=("env_id", "episodes")),
    EndpointSpec("POST", "/network/run-scenario", "network_run_scenario", "Run a local network scenario", request_fields=("scenario",)),
    EndpointSpec("GET", "/release/evidence", "release_evidence", "Return local release evidence bundle metadata"),
    EndpointSpec("GET", "/release/decision/{target}", "release_decision", "Return local release readiness decision for a target"),
    EndpointSpec("GET", "/dashboard/snapshot", "dashboard_snapshot", "Return local dashboard mock snapshot metadata"),
    EndpointSpec("GET", "/visual/state", "visual_state", "Return current Mission Control visual state"),
    EndpointSpec("GET", "/visual/events", "visual_events", "Return recent Mission Control visual events"),
    EndpointSpec("GET", "/visual/schema", "visual_schema", "Return Mission Control visual telemetry schema"),
    EndpointSpec("GET", "/visual/replay/{run_id}", "visual_replay", "Return a saved visual replay snapshot"),
    EndpointSpec("GET", "/network/state", "network_state", "Return current local network state with visual projection"),
    EndpointSpec("POST", "/visual/replay/start", "visual_replay_start", "Run a local visual replay scenario", request_fields=("scenario", "run_id")),
    EndpointSpec("POST", "/compute/plan", "compute_plan", "Build a dry-run Compute Market plan", request_fields=("goal", "task", "policy")),
    EndpointSpec("POST", "/compute/marketplace-plan", "compute_marketplace_plan", "Build a full dry-run Compute Market plan and record economic memory", request_fields=("task", "policy")),
    EndpointSpec("POST", "/compute/quote", "compute_quote", "Generate a deterministic dry-run compute quote", request_fields=("task", "route_id")),
    EndpointSpec("POST", "/compute/route", "compute_route", "Select a policy-bounded dry-run compute route", request_fields=("task", "policy")),
    EndpointSpec("POST", "/compute/payment-plan", "compute_payment_plan", "Generate dry-run payment intent metadata", request_fields=("task", "policy")),
    EndpointSpec("POST", "/compute/simulate-settlement", "compute_simulate_settlement", "Simulate local settlement without moving funds", request_fields=("task", "policy")),
    EndpointSpec("GET", "/compute/providers", "compute_providers", "List local dry-run compute providers"),
    EndpointSpec("GET", "/compute/routes", "compute_routes", "List local dry-run compute routes"),
    EndpointSpec("GET", "/compute/policies", "compute_policies", "List local dry-run compute policies"),
    EndpointSpec("GET", "/compute/capacity", "compute_capacity", "List local dry-run capacity windows"),
    EndpointSpec("GET", "/compute/economic-memory", "compute_economic_memory", "Return dry-run compute economic memory records"),
    EndpointSpec("POST", "/compute/economic-memory/query", "compute_economic_memory_query", "Query dry-run compute economic memory records", request_fields=("route_id", "provider_id", "goal_id")),
)


def endpoint_manifest() -> Mapping[str, Any]:
    return {"endpoints": tuple(endpoint.as_record() for endpoint in API_ENDPOINTS)}
