"""Typed contracts for the Flow Memory cognitive operating system.

The kernel deliberately uses dataclasses and standard-library types so the core can run
without heavyweight services. External adapters can expose the same shapes as Pydantic,
protobuf, JSON Schema, MCP, A2A, or blockchain payloads at the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Mapping, Sequence
from uuid import uuid4


def utc_now() -> datetime:
    """Return a timezone-aware UTC timestamp."""

    return datetime.now(timezone.utc)


def new_id(prefix: str) -> str:
    """Create a domain identifier with a stable prefix and random suffix."""

    return f"{prefix}_{uuid4().hex}"


@dataclass(frozen=True)
class Observation:
    """Input to a cognitive cycle.

    `content` may be text, a structured mapping, or a video payload. Video payloads are
    represented as either a sequence of frames or a mapping with a `frames` key. Frames can
    be nested Python lists or array-like objects accepted by optional ML adapters.
    """

    content: Any
    modality: str = "text"
    source: str = "user"
    metadata: Mapping[str, Any] = field(default_factory=dict)
    observed_at: datetime = field(default_factory=utc_now)

    def as_text(self) -> str:
        if isinstance(self.content, str):
            return self.content
        if isinstance(self.content, Mapping):
            for key in ("text", "prompt", "goal", "description"):
                value = self.content.get(key)
                if isinstance(value, str):
                    return value
        return repr(self.content)


@dataclass(frozen=True)
class Entity:
    """Ventral-stream entity, symbol, or semantic object."""

    label: str
    confidence: float = 1.0
    entity_id: str = field(default_factory=lambda: new_id("entity"))
    attributes: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class MotionGeometry:
    """Dorsal-stream representation of motion, spatial structure, and affordances."""

    trajectories: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    affordances: Sequence[str] = field(default_factory=tuple)
    spatial_relations: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    invariances: Sequence[str] = field(default_factory=tuple)
    confidence: float = 0.0


@dataclass(frozen=True)
class PerceptionOutput:
    """Dual-stream perception output."""

    entities: Sequence[Entity]
    motion_geometry: MotionGeometry
    salience: Mapping[str, float] = field(default_factory=dict)
    latent_state: Mapping[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=utc_now)

    def summary(self) -> str:
        labels = ", ".join(entity.label for entity in self.entities) or "no explicit entities"
        affordances = ", ".join(self.motion_geometry.affordances) or "no explicit affordances"
        return f"entities={labels}; affordances={affordances}"


@dataclass(frozen=True)
class Prediction:
    """Predicted future latent state."""

    state: Mapping[str, Any]
    horizon_steps: int = 1
    confidence: float = 0.5
    prediction_id: str = field(default_factory=lambda: new_id("prediction"))
    created_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class MemoryRecord:
    """Memory item recorded by the layered memory system."""

    kind: str
    text: str
    payload: Mapping[str, Any] = field(default_factory=dict)
    importance: float = 0.5
    record_id: str = field(default_factory=lambda: new_id("memory"))
    created_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class PlanStep:
    """A single typed action proposal, suitable for policy evaluation."""

    action: str
    args: Mapping[str, Any] = field(default_factory=dict)
    required_permission: str = "respond"
    approval_required: bool = False
    economic_value: float = 0.0
    step_id: str = field(default_factory=lambda: new_id("step"))


@dataclass(frozen=True)
class Plan:
    """Policy-checkable plan generated by the reasoner."""

    goal: str
    steps: Sequence[PlanStep]
    plan_id: str = field(default_factory=lambda: new_id("plan"))
    metadata: Mapping[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=utc_now)

    @property
    def has_economic_value(self) -> bool:
        return any(step.economic_value > 0 for step in self.steps)

    @property
    def required_permissions(self) -> set[str]:
        return {step.required_permission for step in self.steps}


@dataclass(frozen=True)
class PolicyDecision:
    """Safety policy result."""

    approved: bool
    reasons: Sequence[str] = field(default_factory=tuple)
    requires_human: bool = False
    risk_level: str = "low"
    decision_id: str = field(default_factory=lambda: new_id("decision"))
    created_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class ActionResult:
    """Result of executing an approved plan."""

    success: bool
    output: Any = None
    step_results: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    side_effects: Sequence[Mapping[str, Any]] = field(default_factory=tuple)
    error: str | None = None
    result_id: str = field(default_factory=lambda: new_id("result"))
    created_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class Evaluation:
    """Prediction-vs-outcome evaluation."""

    surprise_score: float
    metrics: Mapping[str, Any] = field(default_factory=dict)
    evaluation_id: str = field(default_factory=lambda: new_id("evaluation"))
    created_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True)
class CognitiveCycleResult:
    """Full trace of one cognitive-loop tick."""

    observation: Observation
    perception: PerceptionOutput
    prediction: Prediction
    retrieved_memories: Sequence[MemoryRecord]
    plan: Plan
    policy_decision: PolicyDecision
    action_result: ActionResult
    evaluation: Evaluation
    learned: Mapping[str, Any] = field(default_factory=dict)
    economic_settlement: Mapping[str, Any] | None = None
    cycle_id: str = field(default_factory=lambda: new_id("cycle"))
    created_at: datetime = field(default_factory=utc_now)

    @property
    def final_output(self) -> Any:
        return self.action_result.output


ToolHandler = Callable[[Mapping[str, Any]], Any]
