"""Flow Memory Compute Market layer.

Native planning, policy, dry-run payment intents, route selection, and economic
memory for treating compute capacity as an agent-managed economic resource.
"""
from __future__ import annotations

from flow_memory.compute_market.adapters import (
    HTTPQuoteProvider,
    LocalMockComputeProvider,
    MarketplaceProvider,
    QuoteCollector,
    ReservedCapacityProvider,
    StaticConfiguredProvider,
)
from flow_memory.compute_market.config import ComputeMarketConfig, config_from_env
from flow_memory.compute_market.audit_export import AuditCheckpoint, LocalFileAuditExporter, verify_audit_export
from flow_memory.compute_market.controls import (
    DistributedCircuitBreaker,
    DistributedRateLimiter,
    InMemoryCircuitBreaker,
    InMemoryRateLimiter,
    RedisCircuitBreaker,
    RedisRateLimiter,
)
from flow_memory.compute_market.memory import build_economic_memory_record, economic_memory_schema, query_economic_memory
from flow_memory.compute_market.observability import ComputeMarketTelemetry, metric_names, span_names
from flow_memory.compute_market.models import (
    SUPPORTED_UNIT_TYPES,
    AgentBudgetPolicy,
    ComputeCapacityWindow,
    ComputeIntent,
    ComputeMarketPolicy,
    ComputePlan,
    ComputeProvider,
    ComputeQuote,
    ComputeReservation,
    ComputeRoute,
    EconomicMemoryRecord,
    PaymentIntent,
    PaymentPlan,
    PriceCurve,
    ProviderCapability,
    RouteDecision,
    SelectionStrategy,
    SettlementIntent,
    TaskEconomicProfile,
    UnitPriceSnapshot,
)
from flow_memory.compute_market.payment import build_payment_plan, simulate_settlement
from flow_memory.compute_market.planner import (
    build_compute_plan,
    build_task_profile,
    budget_policy_from_payload,
    decide_route,
    discover_providers,
    discover_routes,
    market_policy_from_payload,
    query_memory,
)
from flow_memory.compute_market.provider_contracts import ProviderQuoteContract, validate_provider_quote_contract
from flow_memory.compute_market.service import ComputeMarketService
from flow_memory.compute_market.storage import ComputeMarketStore, audit_event_hash, canonical_audit_payload_hash, migration_plan
from flow_memory.compute_market.storage_backends import PostgresComputeMarketStore, create_compute_market_store, postgres_schema_sql
from flow_memory.compute_market.pricing import collect_quote, collect_quotes, normalize_quote, normalize_quotes
from flow_memory.compute_market.registry import (
    AssetMetadata,
    ExternalProtocolMetadata,
    NetworkMetadata,
    ProviderMetadata,
    RouteMetadata,
    default_assets,
    default_compute_providers,
    default_compute_routes,
    default_networks,
    external_protocols,
    metadata_registry,
    route_metadata,
)
from flow_memory.compute_market.simulation import SIMULATION_SCENARIOS, simulated_routes, simulation_catalog

__all__ = [
    "ComputeMarketConfig",
    "ComputeMarketService",
    "ComputeMarketStore",
    "ComputeMarketTelemetry",
    "DistributedCircuitBreaker",
    "DistributedRateLimiter",
    "AuditCheckpoint",
    "HTTPQuoteProvider",
    "InMemoryCircuitBreaker",
    "InMemoryRateLimiter",
    "LocalFileAuditExporter",
    "LocalMockComputeProvider",
    "MarketplaceProvider",
    "QuoteCollector",
    "ReservedCapacityProvider",
    "PostgresComputeMarketStore",
    "ProviderQuoteContract",
    "StaticConfiguredProvider",
    "RedisCircuitBreaker",
    "RedisRateLimiter",
    "SUPPORTED_UNIT_TYPES",
    "AgentBudgetPolicy",
    "AssetMetadata",
    "ComputeCapacityWindow",
    "ComputeIntent",
    "ComputeMarketPolicy",
    "ComputePlan",
    "ComputeProvider",
    "ComputeQuote",
    "ComputeReservation",
    "ComputeRoute",
    "EconomicMemoryRecord",
    "ExternalProtocolMetadata",
    "NetworkMetadata",
    "PaymentIntent",
    "PaymentPlan",
    "PriceCurve",
    "ProviderCapability",
    "ProviderMetadata",
    "RouteDecision",
    "RouteMetadata",
    "SIMULATION_SCENARIOS",
    "SelectionStrategy",
    "SettlementIntent",
    "TaskEconomicProfile",
    "UnitPriceSnapshot",
    "build_compute_plan",
    "build_economic_memory_record",
    "build_payment_plan",
    "build_task_profile",
    "budget_policy_from_payload",
    "collect_quote",
    "collect_quotes",
    "decide_route",
    "default_assets",
    "default_compute_providers",
    "default_compute_routes",
    "default_networks",
    "discover_providers",
    "discover_routes",
    "economic_memory_schema",
    "config_from_env",
    "audit_event_hash",
    "create_compute_market_store",
    "canonical_audit_payload_hash",
    "external_protocols",
    "market_policy_from_payload",
    "metadata_registry",
    "normalize_quote",
    "normalize_quotes",
    "query_economic_memory",
    "query_memory",
    "route_metadata",
    "metric_names",
    "migration_plan",
    "simulate_settlement",
    "postgres_schema_sql",
    "simulated_routes",
    "simulation_catalog",
    "span_names",
    "validate_provider_quote_contract",
    "verify_audit_export",
]
