import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../src/app/mission-control/page.tsx", import.meta.url), "utf8");
const canvas = readFileSync(new URL("../src/components/mission-control/MissionControlCanvas.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../src/lib/api.ts", import.meta.url), "utf8");
const replay = JSON.parse(readFileSync(new URL("../src/mock-data/local-network-replay.json", import.meta.url), "utf8"));
const embodiment = JSON.parse(readFileSync(new URL("../src/mock-data/live-neural-embodiment.json", import.meta.url), "utf8"));
const config = readFileSync(new URL("../src/lib/mission-control-config.ts", import.meta.url), "utf8");
const controls = readFileSync(new URL("../src/components/mission-control/ReplayControls.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/styles/mission-control.css", import.meta.url), "utf8");
const eventStream = readFileSync(new URL("../src/lib/event-stream.ts", import.meta.url), "utf8");
const runConsole = readFileSync(new URL("../src/lib/run-console.ts", import.meta.url), "utf8");
const runSelector = readFileSync(new URL("../src/components/mission-control/RunSelector.tsx", import.meta.url), "utf8");
const embodimentPanel = readFileSync(new URL("../src/components/mission-control/NeuralEmbodimentPanel.tsx", import.meta.url), "utf8");
const live3DModePanel = readFileSync(new URL("../src/components/mission-control/Live3DModePanel.tsx", import.meta.url), "utf8");

assert.match(page, /The Human Compute Network/);
assert.match(canvas, /AgentNode3D/);
assert.match(canvas, /EconomyEdge/);
assert.match(canvas, /SafetyGate3D/);
assert.match(api, /\/visual\/state/);
assert.match(api, /\/network\/run-scenario/);
assert.match(config, /live local API/);
assert.match(config, /visualFieldMappings/);
assert.match(config, /network:run/);
assert.match(page, /ReplayControls/);
assert.match(page, /RunSelector/);
assert.match(runSelector, /Mission Control Run Selector/);
assert.match(config, /missionControlRunFixtures/);
assert.ok(config.includes("/launch/console/runs"));
assert.ok(config.includes("/launch/bundles/public-alpha"));
assert.match(runConsole, /eventCategoryCounts/);
assert.match(runConsole, /Live Agent Supervisor/);
assert.match(runSelector, /run-status-card/);
assert.match(page, /NeuralEmbodimentPanel/);
assert.match(page, /Live3DModePanel/);
assert.match(live3DModePanel, /Mission Control Live 3D Mode/);
assert.match(live3DModePanel, /data-live-3d-mode/);
assert.match(live3DModePanel, /no_live_provider_calls/);
assert.match(embodimentPanel, /Visible neural embodiment/);
assert.match(config, /live-neural-embodiment/);
assert.match(runConsole, /embodiment/);
assert.match(eventStream, /Local API disconnected/);
assert.match(controls, /Step forward/);
assert.match(controls, /event filters/);
assert.match(canvas, /PredictionArc/);
assert.match(styles, /agent-node-requester/);
assert.match(styles, /economy-slashing/);
assert.match(styles, /live-3d-mode-panel/);
assert.match(styles, /preserve-3d/);
assert.match(styles, /100dvh/);
assert.equal(replay.ok, true);
assert.ok(replay.state.agents.length >= 4);
assert.ok(replay.state.tasks.length >= 1);
assert.equal(embodiment.ok, true);
assert.equal(embodiment.embodiment.gpu_evidence_status, "verified");
assert.equal(embodiment.embodiment.neural_advisory_only, true);
assert.equal(embodiment.embodiment.policy_authority, "policy_engine_and_approval_gate");
assert.ok(embodiment.graph.nodes.some((node) => node.id === "gpu" && node.status === "verified"));
console.log("mission control dashboard scaffold ok");
